FROM python:3.6.4

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/
RUN  pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app

EXPOSE 5000
CMD [ "python", "-m", "flask", "run" ]

#  vim: set ts=8 sw=4 tw=0 ft=dockerfile :
